### ISSUE TITLE
Documents for defining constraints

### ISSUE THREAD

**Issue by fatangare** [HoloClean/holoclean#100]
Hi,

Is there any document explaining how to define different constraints in <data table>_constraints.txt file?

Regards,
Sandeep

**Comment by minafarid** [comment]
Hi Sandeep, the work in this paper discusses the details of denial constraints, including their language.

http://www.vldb.org/pvldb/vol6/p1498-papotti.pdf

**Comment by fatangare** [comment]
Thanks ...closing ticket
