### ISSUE TITLE
dataset: use COPY FROM to load initial CSV file into PostgreSQL

### ISSUE THREAD

**Issue by richardwu** [HoloClean/holoclean#13]
We currently [load the entire CSV file into memory/pandas](https://github.com/HoloClean/holoclean/blob/90668091f1c3baa5a8d19a5874194e8fcec13f6d/dataset/table.py#L29). We treat every column as a `varchar(255)/str` anyways so there is no schema inferencing done (ATM).

This is unscalable for very large datasets. We should instead use the extremely fast [`COPY FROM` statement](http://www.postgresqltutorial.com/import-csv-file-into-posgresql-table/).

**Comment by minafarid** [comment]
From a previous PR #18 comment

`psycopg2` has a `copy` interface described here http://initd.org/psycopg/docs/cursor.html#cursor.copy_from

The code can be  as follows (adopted from https://www.dataquest.io/blog/loading-data-into-postgres/)
```
import psycopg2

conn = psycopg2.connect("host=localhost dbname=postgres user=postgres")
cur = conn.cursor()
with open('user_accounts.csv', 'r') as f:
    # Notice that we don't need the `csv` module.
    next(f)  # Skip the header row.
    cur.copy_from(f, 'users', sep=',')
    
conn.commit()
```
