### ISSUE TITLE
Inconsistency in Dirty and Clean Data Normalization

### ISSUE THREAD

**Issue by ScarletGuo** [HoloClean/holoclean#16]
when loading dirty data, string is lowered
https://github.com/HoloClean/holoclean/blob/90668091f1c3baa5a8d19a5874194e8fcec13f6d/dataset/table.py#L34

when loading clean data, value is only striped but string does not get lowered
https://github.com/HoloClean/holoclean/blob/90668091f1c3baa5a8d19a5874194e8fcec13f6d/evaluate/eval.py#L42

**Comment by ScarletGuo** [comment]
there had a customized function for lowering

**Comment by richardwu** [comment]
I fixed this in #18 for [loading](https://github.com/HoloClean/holoclean/pull/18/files#diff-c25c4677d626699f60b8cf3ab8235f4dR51) and [evaluation](https://github.com/HoloClean/holoclean/pull/18/files#diff-ecc358c3548da3832a30fd12f7f00b04R51).

**Comment by minafarid** [comment]
The fix makes them follow the same normalization process, but it is better to refactor this method out.

**Comment by thodrek** [comment]
Is this fixed? if so please close.

**Comment by minafarid** [comment]
Not yet, a PR in progress is fixing this. #18
