### ISSUE TITLE
PostgreSQL < 9.4 not supported

### ISSUE THREAD

**Issue by pmaetzig** [HoloClean/holoclean#17]
Running holoclean with a postgreSQL version < 9.4 generates the following error:

ERROR setting up domain: For table: pos_values (psycopg2.ProgrammingError) syntax error at or near "WITH ORDINALITY"
LINE 1: ...y(regexp_replace(domain,'[{""}]','','gi'),'|||')) WITH ORDIN...
                                                                             ^

This occurs in domain.py, function store_domains (ll. 57-66). The table pos_values is not created during the store_domains call which breaks the code. 

Cause of the problem is that the "with ordinality" was introduced to postgres first in version 9.4; I can only work with 9.2 at the moment, though.

My quick workaround uses the following query instead of the one in l. 64 (domain.py) in order to create pos_values (based on [this stackoverflow answer](https://stackoverflow.com/a/8767450):

query = "select *, row_number() over (partition by _vid_, _cid_, _tid_) as val_id from (select _vid_, _cid_, _tid_, attribute, rv_val from (select *, unnest(string_to_array(r
    egexp_replace(domain,\'[{\"\"}]\',\'\',\'gi\'),\'|||\')) as rv_val from %s as placeholder_1) as placeholder_2) as placeholder_3" % AuxTables.cell_domain.name

the SQL part in better readable formatting:

"select *, row_number() 
over (partition by _vid_, _cid_, _tid_) 
as val_id 
from (select _vid_, _cid_, _tid_, attribute, rv_val 
         from (select *, unnest(string_to_array(regexp_replace(domain,\'[{\"\"}]\',\'\',\'gi\'),\'|||\')) 
         as rv_val
         from %s) 
         as placeholder_2) 
as placeholder_3"

**Comment by minafarid** [comment]
Hi @pmaetzig thank you very much for your interest in holoclean and for digging deep into this issue and coming up with a solution.

We are currently relying on the features in newer versions of postgresql because they provide necessary optimizations especially in joins.

I understand that you might be limited to a particular version of postgresql. If it is possible for you to use dockers, I suggest starting a postgres docker instance with the latest postgres version 11 as follows

```bash
docker run --name pghc \
    -e POSTGRES_DB=holo -e POSTGRES_USER=holocleanuser -e POSTGRES_PASSWORD=abcd1234 \
    -p 5432:5432 \
    -d postgres:11
```

and you can use `docker start pghc` and `docker stop pghc`  to start/stop the container.

You can find details about this image [here](https://hub.docker.com/_/postgres/) and feel free to ask about any details.

**Comment by pmaetzig** [comment]
Thanks, I was just sharing it in case someone runs into a similar problem and -- as you said -- if someone else is restricted to some older version of postgres. One thing that would be helpful is referencing the optimal postgres version in the readme.

I will try using the docker solution, thanks!

**Comment by thodrek** [comment]
@pmaetzig Please let us know of your experience with docker. More than happy to help in case of any issues.

**Comment by pmaetzig** [comment]
Hi, sorry for the late update -- docker is not an option with my current setup. The most viable solution would be to get an upgrade of postgresql working. When I tried on another machine with an updated version of postgres, this issue did not occur any more.

What else could be affected by using an older postgresql version, potentially?

**Comment by pmaetzig** [comment]
I've managed to upgrade to postgresql 9.4, this fixes the issue as expected. I don't know of any other bugs that occur because of an older postgres version, but this issue can be closed in my opinion.

**Comment by minafarid** [comment]
Thank you Paul for your feedback... One other alternative instead of dockers is to install a local copy of postgresql form its sources. This would be just like any local program.
