### ISSUE TITLE
Investigate missing values from self.single_stats

### ISSUE THREAD

**Issue by richardwu** [HoloClean/holoclean#26]
It was discovered in https://github.com/HoloClean/holoclean/pull/23#discussion_r235134476 that some values were missing from `self.single_stats` even though the values are derived in the same attribute column.

An example of a missing value
```
KeyError: u'surgeryxpatientsxneedingxhairxremovedxfromxthexsurgicalxareaxbeforexsurgery& xwhoxhadxhairxremovedxusingxaxsaferxmethodx(electricxclippersxorxhairxremovalxcreamx\xef\xbf\xbdcxnotxaxrazor)'
```

This is most likely due to an encoding issue when storing data into Postgres and subsequently retrieving it without decoding it properly.

**Comment by thodrek** [comment]
Is this fixed?

**Comment by richardwu** [comment]
Yes this is, feel free to close it.
