### ISSUE TITLE
clean up debugging information

### ISSUE THREAD

**Issue by minafarid** [HoloClean/holoclean#42]
We need to clean up the debugging information that are scattered across the code..

Examples:
* https://github.com/HoloClean/holoclean/blame/dev/repair/featurize/featurize.py#L20
* https://github.com/HoloClean/holoclean/blame/dev/repair/learn/learn.py#L174

This causes some crashes with smaller datasets.

**Comment by ScarletGuo** [comment]
sorry my bad, I did not notice this is committed to dev

**Comment by richardwu** [comment]
I've removed this with #43 and also added a `debug_mode` flag in `self.env['debug_mode']` for all future debug paths.
