### ISSUE TITLE
Using HoloClean for creating labels on tabular numerical datasets

### ISSUE THREAD

**Issue by asstergi** [HoloClean/holoclean#45]
@thodrek Following up on this issue from snorkel (https://github.com/HazyResearch/snorkel/issues/803), I was wondering if there are any examples on how I can use HoloClean to create labels for tabular numerical datasets with the help of labelling functions. 

Any guidance would be really appreciated.

**Comment by asstergi** [comment]
@thodrek could you please provide any guidance on the above question?

**Comment by jondoering** [comment]
Any update on that? Would be really interested, too.

**Comment by DataDoctorNG** [comment]
@thodrek Any update on using HoloClean for tabular data with examples? I have a project I would like to do with HoloClean and would be greatly interested in some examples on how to use it.

**Comment by thodrek** [comment]
We are preparing a release that handles mixed categorical and numerical. It’s in dev currently and soon to be pushed in master.

**Comment by thodrek** [comment]
The latest version on master handles both continuous and discrete values.

**Comment by asstergi** [comment]
@thodrek Thank you for the reply.

One more question though. How should we approach a data labeling problem? If my understanding is correct, the initial value of a sample's label is kind of a 'prior' (in a loose sense) to its final value (after error correction). Is that correct?

If so, how should I initially set the values of the labels? Could I just set them to the same value and let HoloClean sort this out utilizing the constraints?
