### ISSUE TITLE
branch: best branch for testing purposes 

### ISSUE THREAD

**Issue by ariel-ms** [HoloClean/holoclean#86]
Hi,

I just wanted to ask which branch should I use for testing HoloClean on some datasets.
Currently, I am using master however, I see that hcq-embedding-3 is several commits ahead of master. 

Which branch would you suggest me to use?

**Comment by thodrek** [comment]
Hi Ariel, 

I just realized that I told you to use dev while everything from dev had been merged to master. Sorry for this. Branch hcq-embedding-3 is under active development so I wouldn't recommend using it without consulting with us first. 

For now master is your best bet. We can guide you to develop the extensions you may need in terms of featurizers etc. Happy to jump on a call.

Thanks,
Theo

**Comment by ariel-ms** [comment]
Hi Theo,

I will proceed to use master branch. 
Thanks for your help and disposition for guidance.

**Comment by thodrek** [comment]
Happy to help! Please do not hesitate to ping me (email or a phone call works as well) to figure out the best way forward.

Thanks,
Theo
