### ISSUE TITLE
Example that does not use postgres

### ISSUE THREAD

**Issue by m1sta** [HoloClean/holoclean#95]
Hi,

Would it be possible for someone to write a simple example that uses HoloClean with a basic csv, parquet file, or sqlite database instead of postgres? A HoloClean example without the postgres dependency, and even better than initially just uses pytorch-cpu, would make HoloClean feel accessible to a much larger user group.

**Comment by minafarid** [comment]
Hello and thank you for your interest,

HoloClean accepts CSV files as input. But we rely on a DBMS (postgres in this case) to store and query the data and perform various analytics that cannot be done on plain CSV or parquet files, which only store data. 
I would suggest using a docker for postgres if you are not familiar with its setup. Hopefully, this makes it easier for you to try HoloClean out.
